ecommerce_analytics:
  target: ci
  outputs:
    ci:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: ecommerce_dw
      schema: dev
      threads: 4